{% set name = "PyQt-builder" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 267ac1ee1593c67884f3c9cb6566f72a92ca28353050fc9d087433c28c74a889
  patches:
    - patches/0001-Use-conda-sysroot-when-building-recipes.patch
    - patches/0002-disable-test-execution-cross.patch
    - patches/0003-find-sip-distinfo.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyqt-bundle = pyqtbuild.bundle.bundle_main:main
    - pyqt-qt-wheel = pyqtbuild.bundle.qt_wheel_main:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - sip
    - packaging
    - toml

test:
  imports:
    - pyqtbuild
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The PEP 517 compliant PyQt build system
  description: |
    PyQt-builder is the PEP 517 compliant build system for PyQt and projects
    that extend PyQt. It extends the sip build system and uses Qt’s qmake to
    perform the actual compilation and installation of extension modules.

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - JarrettSJohnson
